const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
const {pathToFileURL}=require('node:url');
const {chromium}=require('playwright');
const dir=__dirname,read=n=>JSON.parse(fs.readFileSync(path.join(dir,'data',n+'.json'),'utf8'));
const gifts=read('gifts'),shops=read('shops'),sources=read('sources');
const sourceIds=new Set(sources.map(s=>s.id)),errors=[];
assert.equal(gifts.characters.length,63);assert.equal(new Set(gifts.characters.map(c=>c.id)).size,63);
for(const c of gifts.characters){for(const k of ['loves','likes']){assert.equal(new Set(c[k].map(i=>i.nameJa)).size,c[k].length,c.name+' duplicate gifts');for(const i of c[k]){assert(!/[()]/.test(i.nameJa),c.name+' parser artifact '+i.nameJa);assert(i.nameJa.length>1);for(const id of i.sourceIds)assert(sourceIds.has(id))}}}
for(const l of shops.locations){for(const s of l.shops){assert.equal(new Set(s.items.map(i=>i.nameJa)).size,s.items.length,l.name+' duplicate items');for(const i of s.items){assert(['known','unlimited','unknown'].includes(i.stockStatus));if(i.stockStatus==='known')assert(Number.isInteger(i.stock)&&i.stock>=0);else assert.equal(i.stock,null);for(const id of i.sourceIds)assert(sourceIds.has(id));for(const m of i.exchange)assert(Number.isInteger(m.quantity)&&m.quantity>0)}}}
const cai=gifts.characters.find(c=>c.nameEn==='Cai');assert.equal(cai.loves.length,6);assert.equal(cai.likes.length,1);
const mega=shops.locations.find(l=>l.nameJa==='王都メガエラ');assert.equal(mega.shops.find(s=>s.type==='market').items.find(i=>i.nameJa==='サラミスの菓子').stockStatus,'unlimited');
(async()=>{
const b=await chromium.launch({headless:true,channel:'msedge'}),page=await b.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4175');await page.waitForSelector('.gift-tag');assert.equal(await page.locator('.character').count(),63);
await page.locator('#gift-search').fill('Cai');assert.equal(await page.locator('.character').count(),1);await page.locator('.gift-tag').filter({hasText:'马匹护理工具'}).click();await page.waitForSelector('[data-jump-place]');assert((await page.locator('#purchase').innerText()).includes('库存'));await page.locator('[data-jump-place]').first().click();await page.waitForSelector('#shops-view:not([hidden])');assert((await page.locator('#shop-detail').innerText()).includes('马匹护理工具'));
await page.locator('#shop-search').fill('王都梅加埃拉');await page.locator('[data-shop="market"]').click();assert((await page.locator('#shop-detail').innerText()).includes('∞'));
await page.locator('#shop-search').fill('绝对不存在的商品000');assert.equal(await page.locator('.place-button').count(),0);assert((await page.locator('#shop-detail').innerText()).includes('没有符合'));
await page.locator('#shop-search').fill('海都阿莱克托');await page.locator('[data-shop="vandhal"]').click();assert((await page.locator('#shop-detail').innerText()).includes('×'));await page.locator('.evidence summary').click();assert(await page.locator('.en-table').isVisible());await page.screenshot({path:dir+'/preview-shops.png',fullPage:true});
await page.locator('[data-view="gifts"]').click();await page.locator('#gift-search').fill('');await page.locator('#preference').selectOption('unknown');assert.equal(await page.locator('.character').count(),3);await page.locator('#preference').selectOption('all');await page.locator('[data-character="character-2"]').click();await page.screenshot({path:dir+'/preview-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.screenshot({path:dir+'/preview-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile overflow');
await page.locator('[data-view="shops"]').click();await page.locator('#shop-search').fill('王都梅加埃拉');await page.locator('[data-shop="market"]').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile shop overflow');
await page.locator('[data-view="sources"]').click();assert((await page.locator('#sources').innerText()).includes('English'));
await page.goto(pathToFileURL(path.join(dir,'index.html')).href);await page.waitForSelector('.gift-tag');assert.equal(await page.locator('.character').count(),63,'offline works');assert.equal(errors.length,0,errors.join('\n'));
await b.close();const records=shops.locations.flatMap(l=>l.shops.flatMap(s=>s.items));const result={characters:gifts.characters.length,documentedCharacters:gifts.characters.filter(c=>c.loves.length||c.likes.length).length,locations:shops.locations.length,shopRecords:records.length,knownStockRecords:records.filter(i=>i.stockStatus!=='unknown').length,unknownStockRecords:records.filter(i=>i.stockStatus==='unknown').length,sourcePages:sources.length,checks:['JSON structure and references','Cai gift sample','unlimited stock sample','character search','gift to shop navigation','empty results','shop inventory and English exchange comparison','unknown preferences','mobile layout','source links','offline file loading'],browserErrors:errors};fs.writeFileSync(path.join(dir,'validation.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
})().catch(e=>{console.error(e);process.exit(1)});
